version: '3.7'

services:

  app:
    image: ghcr.io/vertisan/node-boilerplate:latest
    env_file: ../.env
    ports:
      - 80
    networks:
      - default-network

networks:
  default-network: {}
